# Scenario 1
- name: Copy binary from 48 to 49 via control node 44
  hosts: all
  remote_user: weblogic

  tasks:
    - name: copying binaries from source server
      fetch:
        src: "{{ item }}"
        dest: /tmp
        flat: yes
      with_items:
        - /oracle/Softwares/oraInst.loc
        - /oracle/Softwares/wls.rsp
        - /oracle/Softwares/fmw_14.1.1.0.0_wls.jar
      when: inventory_hostname == "aix_server1"   # Copying binaries from source servers

    - name: Copying binary to destination server
      copy:
        src: "/tmp/{{ item | basename }}"
        dest: "/oracle/Softwares/{{ item | basename }}"
        mode: "0755"
      with_items:
        - /oracle/Softwares/oraInst.loc
        - /oracle/Softwares/wls.rsp
        - /oracle/Softwares/fmw_14.1.1.0.0_wls.jar
      when: inventory_hostname == "linux_server1"   # Copying binaries to destination servers

    - name: Installing weblogic in Silent mode on destination server of AIX
      shell: >
        /usr/java8_64/bin/java -jar /oracle/Softwares/fmw_14.1.1.0.0_wls.jar
        -silent
        -responseFile /oracle/Softwares/wls.rsp
        -invPtrLoc /oracle/Softwares/oraInst.loc
      when: ansible_os_family == "AIX"

    - name: Installing weblogic on Linux Server
      shell: >
        /usr/java/jdk1.8.0-x64/bin/java -jar /oracle/Softwares/fmw_14.1.1.0.0_wls.jar
        -silent
        -responseFile /oracle/Softwares/wls.rsp
        -invPtrLoc /oracle/Softwares/oraInst.loc
      when: ansible_system == "Linux"
---
# Scenario 2
- name: Copy WebLogic binaries from source and install on AIX & Linux
  hosts: all
  remote_user: weblogic

  vars:
    src_software_dir: "/oracle/Softwares"
    dest_software_dir: "/oracle/Softwares"

    wls_files:
      - oraInst.loc
      - wls.rsp
      - fmw_14.1.1.0.0_wls.jar

    java_bin:
      AIX: "/usr/java8_64/bin/java"
      Linux: "/usr/java/jdk1.8.0-x64/bin/java"

  tasks:
    - name: Fetch WebLogic binaries from source server (aix_server1)
      fetch:
        src: "{{ src_software_dir }}/{{ item }}"
        dest: "/tmp/wls_binaries/"
        flat: yes
      loop: "{{ wls_files }}"
      when: inventory_hostname == "aix_server1"
      run_once: true

    - name: Ensure destination software directory exists
      ansible.builtin.file:
        path: "{{ dest_software_dir }}"
        state: directory
        owner: weblogic
        group: weblogic
        mode: "0755"

    - name: Copy WebLogic binaries to destination servers
      copy:
        src: "/tmp/wls_binaries/{{ item }}"
        dest: "{{ dest_software_dir }}/{{ item }}"
        owner: weblogic
        group: weblogic
        mode: "0755"
      loop: "{{ wls_files }}"

    - name: Install WebLogic in silent mode (AIX & Linux)
      ansible.builtin.shell: >
        {{ java_bin[ansible_system] }} -jar {{ dest_software_dir }}/fmw_14.1.1.0.0_wls.jar
        -silent -responseFile {{ dest_software_dir }}/wls.rsp -invPtrLoc {{ dest_software_dir }}/oraInst.loc
      args:
        chdir: "{{ dest_software_dir }}"
      when: ansible_system in ["AIX", "Linux"]
